set(TEST_LABEL1 "Infrastructure")
add_subdirectory(stubs)
add_subdirectory(Util)
add_subdirectory(LogErr)
add_subdirectory(VM)
add_subdirectory(Trace)
add_subdirectory(HConfig)
add_subdirectory(Base)
add_subdirectory(TimeMgr)
add_subdirectory(DELayout)
add_subdirectory(Config)
add_subdirectory(ArraySpec)
add_subdirectory(LocalArray)
add_subdirectory(Route)
add_subdirectory(DistGrid)
add_subdirectory(Array)
add_subdirectory(ArrayBundle)
add_subdirectory(IO)
add_subdirectory(Grid)
add_subdirectory(Mesh)
add_subdirectory(XGridGeomBase)
add_subdirectory(GridUtil)
add_subdirectory(LocStream)
add_subdirectory(XGrid)
add_subdirectory(Geom)
add_subdirectory(PointList)
add_subdirectory(Regrid)
add_subdirectory(Field)
add_subdirectory(Container)
add_subdirectory(FieldBundle)
