set(TEST_LABEL1 "Superstructure")
add_subdirectory(State)
add_subdirectory(Component)
if(ESMF_MAPPER_BUILD)
add_subdirectory(Mapper)
endif()
add_subdirectory(InternalState)
add_subdirectory(AttachMethods)
add_subdirectory(InfoAPI)
add_subdirectory(NamedAlias)
add_subdirectory(StateReconcile)
add_subdirectory(AttributeAPI)
add_subdirectory(TraceAPI)
add_subdirectory(WebServices)
add_subdirectory(IOAPI)
add_subdirectory(PreESMFMod)
add_subdirectory(ESMFMod)
# add_subdirectory(AppDriver)
