#!/bin/bash
set -eu

# from build/common.mk

# The rules below generate a valid Fortran file using gcc for the first stage
# of preprocessing.  The 'tr' command substitutes one-for-one, translating:
#   @ into newline to separate lines in multiline macros (the output
#     of the preprocessor is a single line which must be separated again)
#   ^ into # so that other preprocessor commands are ready to be processed by
#     the second runthrough of the preprocessor during the actual compile
#     (These lines are: ^include "fred.h" in the original source to shield
#     them from the first preprocess pass.)
#   | into ' to be able to use single apostrophes in comments.
# The 'sed' command removes any lines which start #pragma GCC . These are
# generated by a couple versions of gcc and confuse the fortran compiler when
# trying to compile the newly generated file.
# The dir, notdir macros below are to be sure to create the .F90 file in the
# original source directory, since the makefile has already changed dirs into
# the mod dir to build.

infile=${1}
outfile=${2}
ESMF_INCDIR=${3}

ESMF_CPP='gcc -E -P -x c -C -nostdinc'
ESMF_SED='sed'

${ESMF_CPP} -I"${ESMF_INCDIR}" "${infile}" | tr "@^|" "\n#'" | ${ESMF_SED} -e '/^#pragma GCC/d' > "${outfile}"
