add_subdirectory(ESMF_CompCreate)
add_subdirectory(ESMF_CompFortranAndC)
add_subdirectory(ESMF_RecursiveComponent)
add_subdirectory(ESMF_ArrayScatterGather)
add_subdirectory(ESMF_Attribute)
add_subdirectory(ESMF_ComplianceChecker)
add_subdirectory(ESMF_ArraySparseMatMul)
add_subdirectory(ESMF_ArrayRedist)
if(ESMF_TESTMPMD)
add_subdirectory(ESMF_ArrayRedistMPMD)
endif()
if(ESMF_TESTSHAREDOBJ)
add_subdirectory(ESMF_ArrayRedistSharedObj)
endif()
add_subdirectory(ESMF_ArrayRedist3D)
add_subdirectory(ESMF_ArrayBundleSparseMatMul)
add_subdirectory(ESMF_ArrayBundleRedist)
add_subdirectory(ESMF_ArrayRedistOpenMP)
add_subdirectory(ESMF_ArrayRedistOpenACC)
add_subdirectory(ESMF_ArraySharedDeSSI)
add_subdirectory(ESMC_FieldRegrid)
add_subdirectory(ESMF_ConcurrentComponent)
add_subdirectory(ESMF_FieldConcurrentComp)
add_subdirectory(ESMF_FieldBundleSMM)
add_subdirectory(ESMF_FieldBundleSMMPacked)
add_subdirectory(ESMF_FieldBundleRedistPacked)
add_subdirectory(ESMF_FieldBundleRegridPacked)
add_subdirectory(ESMF_FieldRedist)
add_subdirectory(ESMF_FieldRedistBlk2Blk)
add_subdirectory(ESMF_FieldRedistBlk2Arb)
add_subdirectory(ESMF_FieldRedistArb2Arb)
add_subdirectory(ESMF_FieldBundleLSRedistArb2Arb)
add_subdirectory(ESMF_FieldBundleLSRedistArb2ArbUngrdDim)
add_subdirectory(ESMF_FieldBundleRedistBlk2Blk)
add_subdirectory(ESMF_FieldBundleRedistBlk2Arb)
add_subdirectory(ESMF_FieldBundleRedistArb2Arb)

add_subdirectory(ESMF_FieldRegrid)
add_subdirectory(ESMF_FieldRegridDisjoint)
add_subdirectory(ESMF_FieldRegridOverlap)
add_subdirectory(ESMF_FieldRegridMesh)
add_subdirectory(ESMF_FieldRegridMeshToMesh)
add_subdirectory(ESMF_FieldRegridLS)
add_subdirectory(ESMF_FieldRegridPatchDisjoint)
add_subdirectory(ESMF_FieldSparseMatMul)
add_subdirectory(ESMF_FieldSharedDeSSI)
add_subdirectory(ESMF_FieldLSRedistArb2Arb)
add_subdirectory(ESMF_FieldLSRedistArb2ArbUngrdDim)
add_subdirectory(ESMF_FieldLSSMM)
add_subdirectory(ESMF_FieldMeshSMM)
add_subdirectory(ESMF_TransferGrid)
add_subdirectory(ESMF_TransferMesh)
add_subdirectory(ESMF_SequentialEnsemble)
add_subdirectory(ESMF_ConcurrentEnsemble)
add_subdirectory(ESMF_DirectCoupling)
add_subdirectory(ESMF_XGridConcurrent)
add_subdirectory(ESMF_XGridSerial)
add_subdirectory(ESMF_Trace)
